CREATE TABLE IF NOT EXISTS Person(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) UNIQUE NOT NULL,
    year_of_birth INT CHECK (year_of_birth > 1900)
);
CREATE TABLE IF NOT EXISTS Book(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id int REFERENCES Person(id) ON DELETE SET NULL,
    title varchar(100) NOT NULL,
    author varchar(100) NOT NULL,
    year int NOT NULL
);